//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_FACTURA
    {
        public int ID_ENC_FACTURA { get; set; }
        public string ID_PRODUCTO { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
        public Nullable<decimal> PRECIO { get; set; }
        public string ID_UBICACION { get; set; }
        public string Comentario { get; set; }
    
        public virtual ENC_FACTURA ENC_FACTURA { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
        public virtual UBICACION UBICACION { get; set; }
    }
}
