//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telefono
    {
        public int ID { get; set; }
        public string Numero_telefono { get; set; }
        public string Id_usuario { get; set; }
        public Nullable<bool> Log_activo { get; set; }
        public Nullable<int> Id_tipo_numero { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
        public virtual Tipo_Telefono Tipo_Telefono { get; set; }
    }
}
